using X39.Util.DependencyInjection.Generator.Tests.TestHelpers;

namespace X39.Util.DependencyInjection.Generator.Tests;

public class ConditionMethodGenerationTests
{
    [Fact]
    public void ParameterlessCondition_GeneratesIfBlock()
    {
        var source = """
            using X39.Util.DependencyInjection.Attributes;

            namespace TestNamespace
            {
                [Singleton<MyService>]
                public class MyService
                {
                    [DependencyInjectionCondition]
                    public static bool IsEnabled() => true;
                }
            }
            """;

        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace X39.Util.DependencyInjection
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class Dependencies
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddDependencies(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MyService).TypeHandle);
                        if (TestNamespace.MyService.IsEnabled())
                        {
                            services.AddSingleton<TestNamespace.MyService>();
                        }

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(source, expected);
    }

    [Fact]
    public void ConditionWithIConfiguration_GeneratesIfBlockWithConfigParam()
    {
        var source = """
            using Microsoft.Extensions.Configuration;
            using X39.Util.DependencyInjection.Attributes;

            namespace TestNamespace
            {
                [Singleton<MyService>]
                public class MyService
                {
                    [DependencyInjectionCondition]
                    public static bool IsEnabled(IConfiguration configuration) => true;
                }
            }
            """;

        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace X39.Util.DependencyInjection
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class Dependencies
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddDependencies(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MyService).TypeHandle);
                        if (TestNamespace.MyService.IsEnabled(configuration))
                        {
                            services.AddSingleton<TestNamespace.MyService>();
                        }

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(source, expected);
    }

    [Fact]
    public void MultipleConditions_GeneratesAndLogic()
    {
        var source = """
            using Microsoft.Extensions.Configuration;
            using X39.Util.DependencyInjection.Attributes;

            namespace TestNamespace
            {
                [Singleton<MyService>]
                public class MyService
                {
                    [DependencyInjectionCondition]
                    public static bool IsEnabled() => true;

                    [DependencyInjectionCondition]
                    public static bool IsConfigured(IConfiguration configuration) => true;
                }
            }
            """;

        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace X39.Util.DependencyInjection
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class Dependencies
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddDependencies(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MyService).TypeHandle);
                        if (TestNamespace.MyService.IsEnabled() && TestNamespace.MyService.IsConfigured(configuration))
                        {
                            services.AddSingleton<TestNamespace.MyService>();
                        }

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(source, expected);
    }
}
