using X39.Util.DependencyInjection.Generator.Tests.TestHelpers;

namespace X39.Util.DependencyInjection.Generator.Tests;

public class CustomNamingTests
{
    private const string Source = """
        using X39.Util.DependencyInjection.Attributes;

        namespace TestNamespace
        {
            [Singleton<MySingleton>]
            public class MySingleton { }
        }
        """;

    [Fact]
    public void CustomClassName_UsesCustomClassName()
    {
        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace X39.Util.DependencyInjection
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class MyServices
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddMyServices(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MySingleton).TypeHandle);
                        services.AddSingleton<TestNamespace.MySingleton>();

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(
            Source, expected,
            hintName: "MyServices.g.cs",
            className: "MyServices");
    }

    [Fact]
    public void CustomNamespace_UsesCustomNamespace()
    {
        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace MyApp.DI
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class Dependencies
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddDependencies(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MySingleton).TypeHandle);
                        services.AddSingleton<TestNamespace.MySingleton>();

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(
            Source, expected,
            namespaceName: "MyApp.DI");
    }

    [Fact]
    public void BothCustom_UsesCustomClassNameAndNamespace()
    {
        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace MyApp.DI
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class MyServices
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddMyServices(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MySingleton).TypeHandle);
                        services.AddSingleton<TestNamespace.MySingleton>();

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(
            Source, expected,
            hintName: "MyServices.g.cs",
            className: "MyServices",
            namespaceName: "MyApp.DI");
    }

    [Fact]
    public void EmptyClassNameAndNamespace_FallsBackToDefaults()
    {
        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace X39.Util.DependencyInjection
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class Dependencies
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddDependencies(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MySingleton).TypeHandle);
                        services.AddSingleton<TestNamespace.MySingleton>();

                        return services;
                    }
                }
            }

            """;

        // Pass empty strings — should fallback to defaults
        GeneratorTestHelper.VerifyGeneratedCode(
            Source, expected,
            className: "",
            namespaceName: "");
    }
}
