using X39.Util.DependencyInjection.Generator.Tests.TestHelpers;

namespace X39.Util.DependencyInjection.Generator.Tests;

public class ScopedGenerationTests
{
    [Fact]
    public void DirectScoped_GenericOneParam_GeneratesCorrectRegistration()
    {
        var source = """
            using X39.Util.DependencyInjection.Attributes;

            namespace TestNamespace
            {
                [Scoped<MyScoped>]
                public class MyScoped { }
            }
            """;

        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace X39.Util.DependencyInjection
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class Dependencies
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddDependencies(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MyScoped).TypeHandle);
                        services.AddScoped<TestNamespace.MyScoped>();

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(source, expected);
    }

    [Fact]
    public void AbstractedScoped_GenericTwoParam_GeneratesCorrectRegistration()
    {
        var source = """
            using X39.Util.DependencyInjection.Attributes;

            namespace TestNamespace
            {
                public interface IMyService { }

                [Scoped<MyService, IMyService>]
                public class MyService : IMyService { }
            }
            """;

        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace X39.Util.DependencyInjection
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class Dependencies
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddDependencies(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MyService).TypeHandle);
                        services.AddScoped<TestNamespace.IMyService, TestNamespace.MyService>();

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(source, expected);
    }
}
