using X39.Util.DependencyInjection.Generator.Tests.TestHelpers;

namespace X39.Util.DependencyInjection.Generator.Tests;

public class SingletonGenerationTests
{
    [Fact]
    public void DirectSingleton_GenericOneParam_GeneratesCorrectRegistration()
    {
        var source = """
            using X39.Util.DependencyInjection.Attributes;

            namespace TestNamespace
            {
                [Singleton<MySingleton>]
                public class MySingleton { }
            }
            """;

        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace X39.Util.DependencyInjection
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class Dependencies
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddDependencies(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MySingleton).TypeHandle);
                        services.AddSingleton<TestNamespace.MySingleton>();

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(source, expected);
    }

    [Fact]
    public void AbstractedSingleton_GenericTwoParam_GeneratesCorrectRegistration()
    {
        var source = """
            using X39.Util.DependencyInjection.Attributes;

            namespace TestNamespace
            {
                public interface IMyService { }

                [Singleton<MyService, IMyService>]
                public class MyService : IMyService { }
            }
            """;

        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace X39.Util.DependencyInjection
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class Dependencies
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddDependencies(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MyService).TypeHandle);
                        services.AddSingleton<TestNamespace.IMyService, TestNamespace.MyService>();

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(source, expected);
    }

    [Fact]
    public void DirectSingleton_NonGenericOneParam_GeneratesCorrectRegistration()
    {
        var source = """
            using System;
            using X39.Util.DependencyInjection.Attributes;

            namespace TestNamespace
            {
                #pragma warning disable CS0618
                [Singleton(typeof(MySingleton))]
                #pragma warning restore CS0618
                public class MySingleton { }
            }
            """;

        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace X39.Util.DependencyInjection
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class Dependencies
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddDependencies(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MySingleton).TypeHandle);
                        services.AddSingleton<TestNamespace.MySingleton>();

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(source, expected);
    }

    [Fact]
    public void AbstractedSingleton_NonGenericTwoParam_GeneratesCorrectRegistration()
    {
        var source = """
            using System;
            using X39.Util.DependencyInjection.Attributes;

            namespace TestNamespace
            {
                public interface IMyService { }

                #pragma warning disable CS0618
                [Singleton(typeof(IMyService), typeof(MyService))]
                #pragma warning restore CS0618
                public class MyService : IMyService { }
            }
            """;

        var expected = """
            // <auto-generated/>
            #nullable enable
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using System.Runtime.CompilerServices;

            namespace X39.Util.DependencyInjection
            {
                /// <summary>
                /// Auto-generated dependency injection registration.
                /// </summary>
                public static class Dependencies
                {
                    /// <summary>
                    /// Registers all attributed services discovered at compile time.
                    /// </summary>
                    public static IServiceCollection AddDependencies(
                        this IServiceCollection services,
                        IConfiguration configuration)
                    {

                        RuntimeHelpers.RunClassConstructor(typeof(TestNamespace.MyService).TypeHandle);
                        services.AddSingleton<TestNamespace.IMyService, TestNamespace.MyService>();

                        return services;
                    }
                }
            }

            """;

        GeneratorTestHelper.VerifyGeneratedCode(source, expected);
    }
}
